config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spots

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :spots do
    resources :comments
  end
  resources :follows
  authenticated :user do
    root 'spots#index', as: :authenticated_root
    get 'users/:id', to: 'users#show', as: :profile
    get 'map', to: 'spots#map'

    post 'spots/follow', to: 'follows#follow', as: :follow_spot
    post 'spots/unfollow', to: 'follows#unfollow', as: :unfollow_spot
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :spot, presence: true, length: { minimum: 3 }
  validates :time_start, presence: true, length: { minimum: 5 }
  validates :time_end, presence: true, length: { minimum: 5 }
  validates :spot, presence: true, length: { minimum: 3 }
  validates :datestring, presence: true
  acts_as_followable
  belongs_to :user
  geocoded_by :location
  after_validation :geocode
  has_many :comments, dependent: :destroy
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @spots = Spot.all.order('spots.datestring ASC', 'spots.time_start DESC')
    @follows = Follow.all.order('follows.created_at ASC')
    @users = User.all
  end

  def map
    @spots = Spot.all
  end

  def show
    @spots = Spot.all
    @spot = Spot.find(params[:id])
    @follows = Follow.all.order('follows.created_at DESC')
    @user = User.find(@spot.user_id)
    @users = User.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(merge_params)

    if @spot.save
      redirect_to @spot
    else
      render 'new'
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])

    if @spot.update(post_params)
      redirect_to @spot
    else
      render 'edit'
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path
  end

  def find
    @spot = Spot.find(params[:id])
  end
private

  def post_params
    params.require(:spot).permit(:spot, :time, :location, :info, :user_id, :username, :avatar, :time_start, :time_end, :date, :datestring)
  end

  def merge_params
    post_params.merge(user_id: current_user.id, username: current_user.username, avatar: current_user.avatar)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/partials/_header.html.erb
<div id="show-header-section">
  <div id="spot-show-title-time">
    <h1 id="spot-show-title"><%= @spot.spot %></h1>
    <h3 id="spot-show-time"><%= @spot.time_start %> - <%= @spot.time_end %></h3>
  </div>
    <h1 id="spot-show-location"><%= @spot.location %></h1>
</div>

app/views/spots/partials/_location_time.html.erb
<div id="locationTimeContainer">
  <div id="spotLocation">
    <h3>Location : <%= @spot.location %></h3>
  </div>
  <div id="spotTime">
    <h3>Time : <%= @spot.time_start %> - <%= @spot.time_end %></h3>
  </div>
</div><hr>

app/views/spots/partials/_lunchers.html.erb
<div id="spot-show-followers-container">
  <div id="spot-show-lunchers-container">
    <h3 id="spot-show-lunchers-title">Lunchers going to <%= @spot.spot %>:</h3>
    <div id="Lunchers">
      <% if @spot.followers.length == 0 %>
          <h4 class="text-welcome-msg" style="font-size: 1vw; text-align: left; padding: 0; padding-bottom: 2vw;">No lunchers for this spot yet :/</h4>
      <% else %>
      <img><% @spot.followers.each do |follower| %>
      <div id="eachLuncher">
          <div id="luncher-info">
          <%= link_to profile_path(follower.id) do %>
                <h3 id="spot-show-follower-username"><%= follower.username%></h3>
          <% end %>
          <% @users.each do |user| %>
            <% if user.id == follower.id %>
              <% if user.diet == "Vegetarian" || user.diet == "vegetarian" %>
                <img class="diet-spot" src="/images/color_diet_icons/carrot.png"></img>
              <% elsif user.diet == "Vegan" || user.diet == "vegan" %>
                <img class="diet-spot" src="/images/color_diet_icons/plant.png"></img>
              <% elsif user.diet == "Pescetarian" || user.diet == "pescetarian" %>
                <img class="diet-spot" src="/images/color_diet_icons/fish.png"></img>
              <% elsif user.diet == "Standard" || user.diet == "standard" || user.diet == "Any" || user.diet == "any" %>
                <img class="diet-spot" src="/images/color_diet_icons/chicken.png"></img>
              <% elsif user.diet == "Lacto-vegetarian" || user.diet == "lacto-vegetarian" || user.diet == "Lacto-Vegetarian" %>
                <img class="diet-spot" src="/images/color_diet_icons/cow.png"></img>
              <% elsif user.diet == "Ovo-vegetarian" || user.diet == "ovo-vegetarian" || user.diet == "Ovo-Vegetarian" %>
                <img class="diet-spot" src="/images/color_diet_icons/egg.png"></img>
              <% else %>
                <p>Love all food !</p>
              <% end %>
                  </div>
          <% end %>
        <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
      <%=render '/spots/partials/spot_comments_content'%>
      <%=render '/spots/partials/spot_comment_form'%>
</div>

app/views/spots/partials/_map_view.html.erb
    <% @places = [] %>

    <% @spots.each do |spot| %>
      <%  @places.push([spot.info, spot.latitude, spot.longitude, spot_path(spot)]) %>
    <% end %>


    <div id="map"></div>

    <script>

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: {lat: 0.524775396e2, lng: -0.1894053e1}
        });
        drop(map);
      }

      var beaches = <%= @places.inspect.html_safe %>
      var markers = [];

      function drop(map) {
   clearMarkers();
   for (var i = 0; i < beaches.length; i++) {
     var beach = beaches[i];
     addMarkerWithTimeout( i * 300, beach[0], beach[3], beach[1], beach[2], map);
   }
 }

      function addMarkerWithTimeout(timeout, title, url, lat, lng, map) {
        window.setTimeout(function() {
            var marker = new google.maps.Marker({
            position: {lat: lat, lng: lng},
            animation: google.maps.Animation.DROP,
            map: map,
            title: title,
            url: url
          });
          markers.push(marker)
          google.maps.event.addListener(marker, 'click', loadURL(marker));
        }, timeout);
      }

      function clearMarkers() {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
      }
      markers = [];
    }

    function loadURL(marker) {
      return function () {
        window.location.href = marker.url;
        }
      }

    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['google_maps_api_key']%>&callback=initMap">
    </script>

    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 90%;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>

app/views/spots/partials/_spot_comment_form.html.erb
<h3 id="spot-show-lunchers-title" style="font-size=1.8vw">Post a comment</h3>
  <%= form_for ([@spot, @spot.comments.build]) do |f| %>
    <%= f.text_field(:content, autocomplete: 'off', id: 'show-comment-enter', :class => 'form-control') %>
    <%= f.submit({:id => 'show-edit-button'}) %>
  <% end %>

app/views/spots/partials/_spot_comments_content.html.erb
  <div id="spot-comments-container">
    <h3 id="spot-show-lunchers-title">Comments:</h3>
<% if @spot.comments.length == 0 %>
    <h4 class="text-welcome-msg" style="font-size: 1vw; text-align: left; padding: 0;">No comments yet :/</h4>
<% else %>
    <% @spot.comments.each do |comment| %>
      <div id="comments-content">
          <% @users.each do |user| %>
            <% if user.id == comment.user_id %>
              <%= link_to profile_path(user.id) do %>
                <% if user.avatar.attached? %>
                  <img style="border-radius: 10px;"<%= image_tag user.avatar.variant(resize: "50x50!")%></img>
                    <% else %>
                      <img src="/images/placeholder_img.jpg"style="height:3vw; width:3vw; border-radius: 10px;"></img>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        <div id="comment-body">
          <%= comment.content%>
        </div>
        <div id="comment-created-at">
          <% if current_user.id == comment.user_id %>
            <%= link_to 'X', [comment.spot, comment],
                                                    method: :delete,
                                                    data: { confirm: 'Are you sure?'},
                                                    class: "red  btn-sm" %>
          <% else %>
            <h4 style="color: white;"><%= comment.created_at %></h4>
          <% end %>
        </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/spots/partials/_spot_info.html.erb
<div id="spotInfo">
  <div id="spotDetails">
    <%= @spot.info %> "
  </div>
</div>
<%= render '/spots/partials/lunchers' %>

app/views/spots/partials/_spot_maps.html.erb
<div id="spotMap">
  <iframe
    id="map"
    width="100%"
    height="200%"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=<%=ENV['google_maps_api_key']%>
    &q=<%="#{@spot.spot}"%>+<%="#{@spot.location}"%>" allowfullscreen>
  </iframe>
</div>

app/views/spots/partials/_spot_user_options.html.erb
<div class="spot-user-option">

  <div id="show-user-buttons">
    <div id="spotInfo">
        <div id="userProfilePicture">
          <% if @user.id == @spot.user_id %>
              <%= link_to profile_path(@user.id) do %>
                <% if @user.avatar.attached? %>
                  <img id="index-avatar" style="border-radius: 10px;"><%= image_tag @user.avatar.variant(resize: "100x100!") %>></img>
                <% else %>
                <img src="/images/placeholder_img.jpg"style="height:6vw; width:6vw; border-radius: 10px;"></img>
                <% end %>
              <% end %>
            <% end %>
            <h3 id="spot-show-username"><%= @spot.username %></h3>
        </div>
    </div>
      <% if current_user.id == @spot.user_id %>
        <button id="show-edit-button"><%= link_to "Edit", edit_spot_path(@spot) %></button>
        <button id="show-delete-button"><%= link_to "Delete", spot_path(@spot), method: :delete,data: {confirm: 'Delete your spot?'}%></button>
    <% else %>
        <%if @spot.followed_by?(current_user)%>
          <%= render 'follows/spot_unfollow_option' %>
        <% else %>
          <%= render 'follows/spot_follow_option' %>
        <% end %>
      <% end %>

  </div>
</div>