config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spots

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :spots do
    resources :comments
  end
  resources :follows
  authenticated :user do
    root 'spots#index', as: :authenticated_root
    get 'users/:id', to: 'users#show', as: :profile
    get 'map', to: 'spots#map'

    post 'spots/follow', to: 'follows#follow', as: :follow_spot
    post 'spots/unfollow', to: 'follows#unfollow', as: :unfollow_spot
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_one_attached :avatar
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update_attribute(:blocked, true)
  end

end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :spot, presence: true, length: { minimum: 3 }
  validates :time_start, presence: true, length: { minimum: 5 }
  validates :time_end, presence: true, length: { minimum: 5 }
  validates :spot, presence: true, length: { minimum: 3 }
  validates :datestring, presence: true
  acts_as_followable
  belongs_to :user
  geocoded_by :location
  after_validation :geocode
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :spots, dependent: :destroy
  has_many :comments
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :avatar, :username, :diet, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @spot = Spot.find(params[:spot_id])
    @comment = @spot.comments.create(merge_params)
    redirect_to spot_path(@spot)
  end

  def destroy
    @post = Spot.find(params[:spot_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to spot_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def merge_params
    comment_params.merge(username: current_user.username,
      user_id: current_user.id, useravatar: current_user.avatar)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def follow
    @spot = Spot.find(params[:id])
    current_user.follow(@spot)
    redirect_to @spot
  end

  def unfollow
    @spot = Spot.find(params[:id])
    current_user.stop_following(@spot)
    redirect_to @spot
  end

  def find
    @spot = Spot.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @spots = Spot.all.order('spots.datestring ASC', 'spots.time_start DESC')
    @follows = Follow.all.order('follows.created_at ASC')
    @users = User.all
  end

  def map
    @spots = Spot.all
  end

  def show
    @spots = Spot.all
    @spot = Spot.find(params[:id])
    @follows = Follow.all.order('follows.created_at DESC')
    @user = User.find(@spot.user_id)
    @users = User.all
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(merge_params)

    if @spot.save
      redirect_to @spot
    else
      render 'new'
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])

    if @spot.update(post_params)
      redirect_to @spot
    else
      render 'edit'
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path
  end

  def find
    @spot = Spot.find(params[:id])
  end
private

  def post_params
    params.require(:spot).permit(:spot, :time, :location, :info, :user_id, :username, :avatar, :time_start, :time_end, :date, :datestring)
  end

  def merge_params
    post_params.merge(user_id: current_user.id, username: current_user.username, avatar: current_user.avatar)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @spots = @user.spots.order(datestring: :asc, created_at: :desc)
    @users = User.all
    @allspots = Spot.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meet&Eat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'spots', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'comments', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['google_maps_api_key']%>&libraries=places"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'home' %>
    <%= javascript_include_tag 'users' %>

    <%= yield %>
  </head>

  <body>

  </body>
</html>

app/views/shared/_navigation.html.erb
  <%= javascript_include_tag 'home' %>
  <nav class="navbar">
    <a class="navbar-brand" href="/"><img class="nav-logo" src="/images/logo.png" alt="Meet & Eat"></a>
  </nav>
<div class="nav-right visible-xs">
  <div class="button" id="btn">
    <div class="bar top"></div>
    <div class="bar middle"></div>
    <div class="bar bottom"></div>
  </div>
</div>
<!-- nav-right -->
<main>

  <nav>
    <div class="nav-right hidden-xs">
      <div class="button" id="btn">
        <div class="bar top"></div>
        <div class="bar middle"></div>
        <div class="bar bottom"></div>
      </div>
    </div>
    <!-- nav-right -->
  </nav>

  <a href="https://codepen.io/tonkec/" class="ua" target="_blank">
    <i class="fa fa-user"></i>
  </a>
</main>

<div class="sidebar">
  <ul class="sidebar-list">
    <li class="sidebar-item"><a id="nav-link" class="profile-link"
    <%= link_to current_user.username, profile_path(current_user.id) %></a></li>
    <li class="sidebar-item"><a id="nav-link"<%= link_to "New spot", new_spot_path %></a</li>
    <li class="sidebar-item"><a id="nav-link"<%= link_to "Sign out", destroy_user_session_path, method: :delete %></a></li>
  </ul>
</div>

<p class="notice" style="display:none;"><%= notice %></p>
<p class="alert" style="display:none;"><%= alert %></p>