config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spots

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :spots do
    resources :comments
  end
  resources :follows
  authenticated :user do
    root 'spots#index', as: :authenticated_root
    get 'users/:id', to: 'users#show', as: :profile
    get 'map', to: 'spots#map'

    post 'spots/follow', to: 'follows#follow', as: :follow_spot
    post 'spots/unfollow', to: 'follows#unfollow', as: :unfollow_spot
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_login.html.erb
<div class="popup-form">
  <a id="close-signin-button" >X</a><br>
  <h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
<div class="field">
  <!-- <h3>Enter your email</h3> -->
  <%= f.email_field :email, id: "email_login", autofocus: true, autocomplete: "off", placeholder: "enter your email", class: "form-control" %>
</div>

<div class="field">
  <!-- <h3>Enter your password</h3> -->
  <%= f.password_field :password, id: "password_login", autocomplete: "off", placeholder: "enter your password", class: "form-control" %>
</div>

<% if devise_mapping.rememberable? -%>
  <div class="field">
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
  </div><br>
<% end -%>

<div class="actions">
  <%= f.submit "Log in", class: "submit-button" %>
</div>
<% end %><br>

</div>

app/views/home/_signup.html.erb
</style>

<div class="popup-form">
  <a id="close-button" >X</a><br>
  <h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), autocomplete: "off") do |f| %>
<div id="error">
    <%= devise_error_messages! %>
    </div>

  <h3>What kind of food do you eat?</h3>
  <div class="diet-options">
    <div class="icon-hover"><img src="/images/color_diet_icons/chicken.png" alt = "omnivore" id = "icon" onclick = "omniAdd()"></div>
    <div class="icon-hover"><img src="/images/color_diet_icons/plant.png" alt = "vegan" id = "icon" onclick = "veganAdd()"></div>
    <div class="icon-hover"><img src="/images/color_diet_icons/cow.png" alt = "lacto vegetarian" id = "icon" onclick = "lactoAdd()"></div>
    <div class="icon-hover"><img src="/images/color_diet_icons/carrot.png" alt = "vegetarian" id = "icon" onclick = "veggieAdd()"></div>
    <div class="icon-hover"><img src="/images/color_diet_icons/fish.png" alt = "pescetarian" id = "icon" onclick = "pesciAdd()"></div>
    <div class="icon-hover"><img src="/images/color_diet_icons/egg.png" alt = "ovo-vegetarian" id = "icon" onclick = "ovoAdd()"></div>
  </div>

  <div class="field">
    <%= f.text_field :diet, autofocus: true, id: "diet-pref", autocomplete: "off", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.text_field :username, autofocus: true, autocomplete: "off", placeholder: "pick a username", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.email_field :email, id: "email_signup", autofocus: true, autocomplete: "off",  placeholder: "enter your email", class: "form-control" %>
  </div>

  <div class="field">
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, id: "password_signup", autocomplete: "off", placeholder: "make a password", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "confirm your password", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", class: "submit-button" %>
  </div><br>
<% end %>

</div>

<style>
  .field {
    margin: 20px;
  }
  #signup-small-button {
    color: white;
    backround-color: white;
    font-size: 2vw;
  }
input[type=text],input[type=email],input[type=username],input[type=password],input[type=password_confirmation]  {
  background-color: transparent;
  font-size: 1vw;
  color: white;
  text-align: center;
  margin: 10px;
  border-style: solid;
  border-width: 3px;
  border-radius: 20px;
  border-color: white;
  box-shadow:none !important;
  padding: 30px;
}
input::-webkit-input-placeholder {
  color: white!important;
}
</style>

app/views/home/index.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <body class="home">
    <div class="bkg-animated">
      <div class="home-logo">M + E</div><br>
      <div class="button-container">
        <button class="home-buttons-signup" onclick="openForm()" id="signup-button">SIGN UP</button>
        <button class="home-buttons-login" id="signin-button">LOGIN</button>
      </div>
    </div>

  <div id="formGroupSignUp">
    <%= render 'signup' %>
  </div>

  <div id="formGroupSignIn">
    <%= render 'login' %>
  </div>

</body>
</html>