config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spots

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :spots do
    resources :comments
  end
  resources :follows
  authenticated :user do
    root 'spots#index', as: :authenticated_root
    get 'users/:id', to: 'users#show', as: :profile
    get 'map', to: 'spots#map'

    post 'spots/follow', to: 'follows#follow', as: :follow_spot
    post 'spots/unfollow', to: 'follows#unfollow', as: :unfollow_spot
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update_attribute(:blocked, true)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def follow
    @spot = Spot.find(params[:id])
    current_user.follow(@spot)
    redirect_to @spot
  end

  def unfollow
    @spot = Spot.find(params[:id])
    current_user.stop_following(@spot)
    redirect_to @spot
  end

  def find
    @spot = Spot.find(params[:id])
  end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_spot_follow_option.html.erb
  <div id="show-user-buttons">
    <%= form_tag follow_spot_path(id: @spot.id), method: :post, data: {confirm: 'Joined a lunch spot!'}, remote: true do  %>
    <button id="show-edit-button"><%= link_to 'Join Spot', follow_spot_path(id: @spot.id), method: :post, data: {confirm: 'Joined a lunch spot!'}, remote: true %></button>
    <% end %>
  </div>

app/views/follows/_spot_follower_list.html.erb
<img><% spot.followers.each do |follower| %>
  <%= link_to profile_path(follower.id) do %>
    <% if follower.avatar.attached? %>
      <%= image_tag follower.avatar.variant(resize: "50x50!"), class: "tar rounded-circle" %>
    <% else %>
      <%= image_tag gravatar_image_url(follower.email, size: 75), height: 50, width: 50, class: "tar rounded-circle" %>
    <% end %>
  <% end %>
<% end %>
</img>

app/views/follows/_spot_unfollow_option.html.erb
<div id="show-user-buttons">
  <%= form_tag unfollow_spot_path(id: @spot.id), method: :post, data: {confirm: 'You monster.'}, remote: true do  %>
  <button id="show-edit-button"><%= link_to 'Leave Spot', unfollow_spot_path(id: @spot.id), method: :post, data: {confirm: 'You monster.'}, remote: true%></button>
  <% end %>
</div>